import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'try next.js',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <a href='/'>Home</a>
        </nav>
        {children}
        <nav>
          <a href='/'>Footer</a>
        </nav>

      </body>
    </html>
  )
}
